version: "2.3"
services:
  magic-cards:
    image: jonmaddox/magic-cards
    volumes:
      - "./magic-cards/config:/usr/src/app/config"
    ports:
      - 5000:5000
    restart: always
    devices:
      - "/dev/input/event0:/dev/input/event0"
    networks:
      - default
  led-desk:
    image: kverhaar/led-desk
    build: ./led-desk
    environment:
      - MQTT_HOST=172.20.10.7
      - MQTT_BASE_TOPIC=led-desk-downstairs
    networks:
      - default
