automation:
  - alias: guessgame_start
    trigger:
      - platform: event
        event_type: magic_card_scanned
        event_data:
          card_type: event
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ trigger.event.data.card_uri.split('|')[0] == 'start'}}"
        - condition: state
          entity_id: input_text.guessgame_state
          state: "idle"
    action:
      - service: script.guessgame_start
        data_template:
          collection: "{{ trigger.event.data.card_uri.split('|')[1] }}"
      # - service: input_text.set_value
      #   data:
      #     entity_id: input_text.animalguess_state
      #     value: "question"

  - alias: ask_animalguess_question
    trigger:
      - platform: state
        entity_id: input_text.animalguess_state
        to: "question"
    action:
      - service: script.speak
        data_template:
          text: "Hier is een vraag!"
      - service: input_text.set_value
        data:
          entity_id: input_text.animalguess_state
          value: "waiting_answer"

script:
  ## Call with
  ## {{ collection }} (collection from which the question should be pulled)
  guessgame_start:
    sequence:
      - service: script.speak
        data_template:
          text: "Laten we een spelletje spelen!"
      - service: input_text.set_value
        data:
          entity_id: input_text.guessgame_state
          value: "starting"
      - service: input_text.set_value
        data_template:
          entity_id: input_text.guessgame_collection
          value: "{{ collection }}"
