FROM balenalib/raspberrypi3-python:3

ENV MQTT_HOST=broker.lan
ENV MQTT_BASE_TOPIC=led-desk-downstairs

ADD requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

ADD led-desk.py led-desk.py

ENTRYPOINT [ "python", "-u", "led-desk.py"]
