FROM balenalib/raspberry-pi-python:3

ENV MQTT_HOST=home.lan
ENV MQTT_BASE_TOPIC=led-desk-downstairs

RUN apt-get update && apt-get install -y build-essential

ADD requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

ADD led-desk.py led-desk.py

ENTRYPOINT [ "python", "-u", "led-desk.py"]
